### ISSUE TITLE
[TRACKER] Kodi 21 plugins

### ISSUE THREAD

**Issue by parona-source** [kodi-overlay/kodi-overlay#2]
Now that kodi-21 is in the gentoo repo it would be good time see about getting plugins bumped as well.

Here is a task list with all plugins.

- [x] media-plugins/kodi-audiodecoder-modplug
- [x] media-plugins/kodi-audiodecoder-nosefart
- [x] media-plugins/kodi-audiodecoder-sacd
- [x] media-plugins/kodi-audiodecoder-sidplay
- [x] media-plugins/kodi-audiodecoder-snesapu
- [x] media-plugins/kodi-audiodecoder-stsound
- [x] media-plugins/kodi-audiodecoder-timidity
- [x] media-plugins/kodi-audiodecoder-vgmstream
- [x] media-plugins/kodi-audioencoder-flac
- [x] media-plugins/kodi-audioencoder-lame
- [x] media-plugins/kodi-audioencoder-vorbis
- [x] media-plugins/kodi-audioencoder-wav
- [x] media-plugins/kodi-game-libretro
- [x] media-plugins/kodi-game-libretro-bnes
- [x] media-plugins/kodi-game-libretro-dosbox
- [x] media-plugins/kodi-game-libretro-nestopia
- [x] media-plugins/kodi-game-libretro-snes9x
- [x] media-plugins/kodi-game-libretro-twentyfortyeight
- [x] media-plugins/kodi-imagedecoder-heif
- [x] media-plugins/kodi-imagedecoder-raw
- [x] media-plugins/kodi-inputstream-adaptive
- [x] media-plugins/kodi-inputstream-ffmpegdirect
- [x] media-plugins/kodi-inputstream-rtmp
- [x] media-plugins/kodi-peripheral-joystick
- [x] media-plugins/kodi-pvr-argustv
- [x] media-plugins/kodi-pvr-demo
- [x] media-plugins/kodi-pvr-dvblink
- [x] media-plugins/kodi-pvr-dvbviewer
- [x] media-plugins/kodi-pvr-filmon
- [x] media-plugins/kodi-pvr-hts
- [x] media-plugins/kodi-pvr-iptvsimple
- [x] media-plugins/kodi-pvr-mediaportal-tvserver
- [x] media-plugins/kodi-pvr-mythtv
- [x] media-plugins/kodi-pvr-nextpvr
- [x] media-plugins/kodi-pvr-njoy
- [x] media-plugins/kodi-pvr-pctv
- [x] media-plugins/kodi-pvr-stalker
- [x] media-plugins/kodi-pvr-vbox
- [x] media-plugins/kodi-pvr-vdr-vnsi
- [x] media-plugins/kodi-pvr-vuplus
- [x] media-plugins/kodi-pvr-wmc
- [x] media-plugins/kodi-pvr-zattoo
- [x] media-plugins/kodi-screensaver-asteroids
- [x] media-plugins/kodi-screensaver-asterwave
- [x] media-plugins/kodi-screensaver-biogenesis
- [x] media-plugins/kodi-screensaver-cpblobs
- [x] media-plugins/kodi-screensaver-greynetic
- [x] media-plugins/kodi-screensaver-matrixtrails
- [x] media-plugins/kodi-screensaver-pingpong
- [x] media-plugins/kodi-screensaver-pyro
- [x] media-plugins/kodi-screensaver-shadertoy
- [x] media-plugins/kodi-screensaver-stars
- [x] media-plugins/kodi-vfs-libarchive
- [x] media-plugins/kodi-vfs-rar
- [x] media-plugins/kodi-vfs-sftp
- [x] media-plugins/kodi-visualization-fishbmc
- [x] media-plugins/kodi-visualization-goom
- [x] media-plugins/kodi-visualization-projectm
- [x] media-plugins/kodi-visualization-shadertoy
- [x] media-plugins/kodi-visualization-spectrum
- [x] media-plugins/kodi-visualization-starburst
- [x] media-plugins/kodi-visualization-waveform

**Comment by dguglielmi** [comment]
I will take a look at this. Probably this weekend.

**Comment by dguglielmi** [comment]
Well, it's the first step.

The plugins were bumped to the latest version available and build fine (at least on my system), but I have to review/fix some dependencies requirement.

I made the choice to build libretro libraries as a part on the ebuild for (media-plugins/kodi-game-libretro-*) because:
- It's the easiest way to test the addons (at least for now)
- When libretro libraries are available "system-wide" via "games-emulation/libretro-XYZ", they are just duplicated as a part of the installation process into "/usr/lib64/kodi/addons/game.libretro.X/game.libretro.X.so" but why duplicate them for "no reason" ?

So we have multiple choices here:
- Keep them embded with the ebuild (PRO: we do not depend on anything else and we can stay or upgrade our own version. We ensure Kodi compatibility without thinking about other apps. CON: we do not share them with other libretro applications)
- Depend on "games-emulation/libretro-X" and rebuild the addons when upgrades are made and keep in sync Kodi and other libretro apps (con: we duplicate the library)
- Find a way to symlink the Kodi addons library to the system-wide libretro version (We may have to patch cmake helpers from "media-tv/kodi" to do so)

@parona-source : What is your opinion on that ?

**Comment by parona-source** [comment]
Thanks for doing all this, I appreciate it.

With the libretro I'm unsure of what you mean.

They don't appear to be identical (unless im looking at the wrong ebuilds/libraries).

```
$ md5sum /usr/lib64/kodi/addons/game.libretro*/*
e29be2ae5cdef4dba0057ac8138a6535  /usr/lib64/kodi/addons/game.libretro.2048/game.libretro.2048.so
6a21b1b0c9521d273ae59a86671041c5  /usr/lib64/kodi/addons/game.libretro.bnes/game.libretro.bnes.so
f031cec577b0e12938e1a6ce183d0b1b  /usr/lib64/kodi/addons/game.libretro/game.libretro.so
f031cec577b0e12938e1a6ce183d0b1b  /usr/lib64/kodi/addons/game.libretro/game.libretro.so.21.0
f031cec577b0e12938e1a6ce183d0b1b  /usr/lib64/kodi/addons/game.libretro/game.libretro.so.21.0.6
42e75fd0a9e6695dbc94b9f2d70346c2  /usr/lib64/kodi/addons/game.libretro.snes9x/game.libretro.snes9x.so
```

**Comment by dguglielmi** [comment]
I mean, if you look for example the ebuild kodi-game-libretro-bnes/kodi-game-libretro-bnes-0.83.0.8 from ::gentoo, it depend on games-emulation/libretro-bnes

 - games-emulation/libretro-bnes: builds and install the libretro emulator into "/usr/lib64/libretro/bnes_libretro.so".

- media-plugins/kodi-game-libretro-bnes-0.83.0.8: doesn't build the libretro emulator itself, it "just" make a copy of the libretro library emulator from "/usr/lib64/libretro/bnes_libretro.so" into "/usr/lib64/kodi/addons/game.libretro.bnes/game.libretro.bnes.so"

With that in mind, I don't have a strong ideas of what is the best to do with the 3 suggestions I write in my previous message.

**Comment by parona-source** [comment]
After having time to properly look at it, Im going towards the symlink solution as the best one. 

Status quo has the issue that the libraries will go out sync so its a no go long term, just putting them in DEPEND won't solve it either as rebuilds can only be triggered with subslots, this force adding a subslot change in every version of the libretro dependencies.

How is a different question, easiest to do in the ebuild of course. But I haven't inspected cmakes solutions thoroughly, patching kodi may be viable.

**Comment by parona-source** [comment]
https://github.com/parona-source/gentoo/tree/kodi-plugins

Started with seeing how to transfer these changes to ::gentoo.

One thing is that the changes to kodi-addons are large enough that it needs to be revbumped. This may get pushback but Im going with it for now for expediency.

I also had to modify the eclass to handle -9999 packages, but ill see about adding those changes here first.

`for i in media-plugins/kodi-* ; do cp ~/sources/kodi-overlay/${i}/*.ebuild ${i}; git add ${i}; pkgdev commit -T "Co-authored-by:David GUGLIELMI <david.guglielmi@gmail.com>"; done`

`for i in media-plugins/kodi-* ; do cp ~/sources/kodi-overlay/${i}/*.ebuild ${i}/*-9999.ebuild; sed -i -e '/KODI_ADDON_TAG/d' -e '/KEYWORDS/d' ${i}/*-9999.ebuild ; git add ${i}; pkgdev commit ; done`

**Comment by dguglielmi** [comment]
@parona-source : I just check about updates and media-plugins/kodi-peripheral-joystick is bumped from 21.1.15 to 21.1.18, can you add it ? (I just pushed it here)

**Comment by parona-source** [comment]
Ill device some script to update it. Currently just scoping out any issues that there might be.

I dont think ill open a PR today atleast.

**Comment by parona-source** [comment]
Actually noticed some minor incorrect changes.

Some of the licenses were changed from GPL-2+ -> GPL-2 in this repo, and its actually incorrect.

GPL license are bit hard to figure out with the "or later" clause, but the thing is that contents of LICENSE wont make it obvious if the or later clause is in effect or not. 

To make sure of that you have to check other sources in the repo, for example the license headers in files and if other metadata that uses SPDX should make it clear.

So the easiest place to check with addons is the xml file like here https://github.com/xbmc/visualization.waveform/blob/Omega/visualization.waveform/addon.xml.in#L13

**Comment by dguglielmi** [comment]
My bad. Probably a couple of "unlucky" copy/paste. Do you want me to check and fix that here, or should I wait for you to push your last changes here ?

**Comment by parona-source** [comment]
Feel free to check and fix at your pace. I havent yet made any commits for this repo, only playing around with WIP branch for ::gentoo.

Even so rebasing is no fuss.

**Comment by parona-source** [comment]
Like one chore for me is checking bugs against all the packages and seeing if any can or should be addressed.

**Comment by dguglielmi** [comment]
To make a quick check, l just made a script to compare the licenses from ::gentoo and from the overlay and fix the diff.

```
#!/bin/bash

for e in media-plugins/*/*.ebuild
do
  D=$(dirname ${e})
  OVERLAY_LIC=$(sed -ne 's#LICENSE="\(.*\)"#\1#p' ${e})
  if [ ! -d /var/db/repos/gentoo/${D} ]; then
    continue
  fi
  GENTOO_LIC=$(sed -ne 's#LICENSE="\(.*\)"#\1#p' /var/db/repos/gentoo/${D}/*.ebuild | sed -ne '1p')
  if [ ! "${OVERLAY_LIC}" == "${GENTOO_LIC}" ]; then
    echo -e "${D}"
    echo -e "\e[1;31m"
    echo "::kodi-overlay: ${OVERLAY_LIC}"
    echo "::gentoo: ${GENTOO_LIC}"
    echo -e "\e[0;m"
  fi
done
```

But some ebuilds in ::gentoo are also not "compliant" with the licence in the plugin addon.xml file, I'll take a look a this maybe tomorrow.

**Comment by parona-source** [comment]
https://github.com/kodi-overlay/kodi-overlay/blob/main/Scripts/kodi-addon-diff

Added some of this into the script I had for dependencies.

**Comment by dguglielmi** [comment]
@parona-source : I made some progress with live ebuilds, I'll push them soon with something like this

https://github.com/kodi-overlay/kodi-overlay/commit/1e58a543ff5ebc205fe3b68948d1f1bbfbfdfbcd

**Comment by parona-source** [comment]
with live ebuilds i did this https://github.com/kodi-overlay/kodi-overlay/commit/02b4be009009183d7b5a42105e6b25eea50df1d5.

it would look like this https://github.com/parona-source/gentoo/commit/efa2aea7a17b5bcdab96f739957930ad3eb8c792

**Comment by dguglielmi** [comment]
@parona-source : live ebuilds are here. Finally! I added 21.9999 when supported but if we don't want them we can remove them and remove also https://github.com/kodi-overlay/kodi-overlay/blob/4d9003a8bf4459e6d9b6894ea39cee8a73b22fad/eclass/kodi-addon.eclass#L79
